### PR TITLE
New cards-based Sampa web

### PR DESCRIPTION
**Pull request by bholt**
Hey to anyone interested,

I'm trying out a new design for the webpage and would like some feedback. I thought I'd try and get more of our exciting content into the homepage so people don't have to navigate around so much. So my plan is to have thumbnails (cards) of all the project pages on the landing page. These will just be auto-generated from info in the header of each project page, so adding more projects is as simple as adding pages to the `_projects` directory (and specifying the relevant metadata).

I also wanted to revamp how we do our list of people so it would fit better on the homepage. And in order to make it easier to associate projects with people, I thought we could have a thumbnail picture for each person, and then under each project have the pictures of the people involved.

You can checkout what I have so far here: http://sampa.cs.washington.edu/cards/. If you want to mess with it, you can just checkout the `cards` branch, and either `jekyll serve` locally, or `make deploy` to push to /cards (it won't overwrite the real sampa page).

/cc @jamesbornholt @luisceze @amritamaz

### CODE REVIEW

**Comment by bmyerz** [comment]
Cool idea, looks like we haven't done much face work since the [bootstrapping of 2014](https://web.archive.org/web/20140221055254/http://sampa.cs.washington.edu/). I like the cards for the projects and faculty that have blurbs.  But I'm not sure about all of the people being cards. For example, will alumni be more than name+link+1liner? If not I'd make them not cards because they just take up extra space.

**Comment by amritamaz** [comment]
Thanks for doing this! I like the project cards a lot. I like them so much that now the news section is looking terribly dated to me.

I'm undecided on the people cards, though - I agree w Myers about the alumni cards taking up space, and on mobile that is true for pretty much all the cards. I also wish the faces were a little bigger. Thumbnails are nice on projects but look too small on the people cards.

**Comment by carlodelmundo-zz** [comment]
Brandon, this looks fantastic! +1 on the cards idea as well. Gonna also go
with "cards look good on projects but not people" bandwagon.

**Comment by bholt** [comment]
Thanks for the feedback everyone! We were discussing making the people section be two columns: faculty/staff on one side, students on the other, and making them not cards. Maybe we should go back to the `dl`/`dt` thing from before. If anyone has a vision of what the people entities should look like, I'd love some ideas, I'm just not coming up with any creative ideas right now.

@amritamaz if you have any ideas on how to make the News section better, I'd love to hear/see them. I agree, it definitely doesn't feel like it fits. And I don't think _card all the things!_ is the correct solution there either. ;)

**Comment by arminalaghi** [comment]
Thanks again Brandon. I think it looks very nice.
I like the cards on projects AND people; with the exception that the
description on people's cards should not exceed one line.

As for the news, can we do something like a timeline with the most recent
item showing full description of the news (e.g., "Carlo and Vincent just
went to MEMSYS http://memsys.io/ to present our paper
http://homes.cs.washington.edu/%7Ecdel/papers/MEMSYS_2015.pdf on ....")?
The rest of the items can appear on the timeline with face/project
thumbnails (e.g., #3 can be just the Grappa thumbnail showing on the
timeline). People can click on those to expand the news.

Cheers,
Armin

**Comment by sampsyo** [comment]
ON BEHALF OF THE ALUMNI I OBJECT TO BEING ELIMINATED FROM THE FRONT PAGE just kidding this looks great y'all

**Comment by bholt** [comment]
@sampsyo you're on the homepage! even better than when you were a grad student. :P

Everyone else, check out the new people section design. What do you all think?

**Comment by jamesbornholt** [comment]
I like this a lot. I would lean towards deleting the faculty/staff bios entirely though (or just keep the first sentence).

**Comment by bholt** [comment]
The bios certainly aren't very consistent. I'd like the faculty at least to have a blurb about what they focus on, like Dan does. With the bigger pics, grads also have pleny of room for a short blurb if we want to allow that...

**Comment by jamesbornholt** [comment]
I think even short blurbs make the page too busy (remember it's going to get heavier as we add more projects)—I would prefer to just put "Associate Professor" etc under faculty and nothing else. But happy to defer to other folks on that; design by committee etc etc. Also, it's now really bothering me that neither faculty nor researchers are in alphabetical order :-)

**Comment by jamesbornholt** [comment]
On the news section: an easy tweak could be to copy the style from [uwplse.org](http://uwplse.org) or [my homepage blog](http://homes.cs.washington.edu/~bornholt/), where entries don't wrap below dates, dates are shorter, and (on my page) dates are right-aligned. That might be enough to make it feel less outdated (especially the alignment thing).

**Comment by bholt** [comment]
@jamesbornholt as long as we don't have to put up with your font I'm game.

**Comment by luisceze** [comment]
+1 on both accounts! Thanks so much for doing this!!

-Luis
(this message made short and unintelligible by my iPhone)

**Comment by jamesbornholt** [comment]
I undid the accidental merge, but we have to open a new pull request: #3.

**Comment by bholt** [comment]
And now it's reincarnated again in #4.

**Pull request merged**
