### PR TITLE
New cards-based Sampa web, attempt #3

### PR DESCRIPTION
**Pull request by bholt**
Re-reopening after failing to understand revert-reverting. Much easier to just go back in time and rewrite history. This is the alternate future version of #2 (and #3) where we have hoverboards.

backtothefuture

### CODE REVIEW

**Comment by bholt** [comment]
Actually that hip news thing is weird, it doesn't wrap right when it gets narrow. @jamesbornholt wanna fix it, or anyone got any cool ideas for the news feed worked out? @amritamaz?

**Comment by bholt** [comment]
Also, if anyone wants to start making their project pages, just add your own file to `_projects` and define the right metadata (see `_projects/claret.md` for an example).

**Comment by bmyerz** [comment]
Looks great!

**Comment by bholt** [comment]
Hey @jamesbornholt @amritamaz @bmyerz @carlodelmundo @agent-lee, could you add some of your projects to the new _projects folder? See any of mine for examples. Thanks!

Once we have some non-me projects, and everyone has had a chance to make changes to the look and feel, I think we can probably go ahead and deploy this.

**Comment by amritamaz** [comment]
question for @luisceze - should we add Visvesh to some section of the website? I want to include him on the near-sensor project page but am unsure if he should be listed as a faculty member of Sampa or a collaborator

**Comment by bholt** [comment]
I was having the same question actually about the Syslab folks. Seems like there's a fine distinction between Sampa member and collaborator...

**Comment by luisceze** [comment]
@amrita yes please. lets add him as collaborators.

**Comment by luisceze** [comment]
whatever works. just make sure you let people know they are being listed :)

**Pull request merged**
